### ISSUE TITLE
Extract images and videos from a JWPUB

### ISSUE THREAD

**Issue by livrasand** [MrCyjaneK/jwapi#23]
Hello, we were chatting a bit together here. I am the author of an app called [Attendant Zoom](https://goattendant.com/) programmed in Visual Basic .NET. I would like to know how I can extract all the images and videos from JWPUB. I can currently edit the JWPUBs without problems in CyberChef as explained. Do you know how I can extract the images and videos?

**Comment by MrCyjaneK** [comment]
https://github.com/MrCyjaneK/jwapi/blob/master/docs/jwpub/index.md#content

like this?

**Comment by livrasand** [comment]
It's really not what I'm looking for, let me explain, I really need professional help. I am a Jehovah's Witness and the author of Attendant Zoom, an app for sharing media on video conferencing platforms, in Kingdom Halls, and in Assembly Halls. It is programmed in Visual Basic .NET.

I am trying to make Attendant Zoom standalone, and download the media automatically, this is what I have so far:

I think this would be the algorithm


Yo. Download the Activity Guide in JWPUB format directly from JW.ORG with the GETPUBMEDIALINKS API
ii. Unzip the JWPUB (composed of a *.json and a folder called contents, inside contents is the *.db file which is named after the *.jwpub file)
iii. Access the database
IV. Export the KeySymbol Track MepsLanguageIndex IssueTagNumber columns of the Multimedia table in *.txt format
v. Read the *.txt files and fill in the following URL: https://b.jw-cdn.org/apis/mediator/v1/media-items/{DATA FROM DATABASE}VIDEO?clientType=www
saw. Access the URL and get the JSON content
vii. Parse the JSON
viii. Download the correct video r720P
ix. Save the video in a specific folder
x. Move the corresponding images from the contents folder to the same specified folder above

My application, once the multimedia is in that folder, will show the images and videos. I found a program in C# that allows me to extract information from the database to TXT, the JWPUB files have a database, so the idea is to extract the links of the videos from the database and have Attendant Zoom read the file. text that will contain the link and download it.

The C# application generates some TXT files that contain the content of the columns: KeySymbol · Track · MepsLenguageIndex · IssueTagNumber, from the Multimedia table, that content is used to complement this URL:
https://b.jw-cdn.org/apis/mediator/v1/media-items/{S}/pub-{sjjm}_{1}_VIDEO?clientType=www

This URL gives me a JSON file that contains the 5 formats to download, I looked at this on the Internet https://analisisyprogramacionoop.blogspot.com/2019/12/parsear-manualmente-json-file.html, I think it could help me read the JSON file, but I still don't see how I can select the one from r720P and download that video.

I would greatly appreciate your contribution if you could help me, I will give you credits within my app and my website. My app is totally free and is maintained as a community. I need help urgently

**Comment by temporarium** [comment]
That seems like a lot of extra work. Have you considered just parsing the html from wol.jw.org to get the links for the videos?

Also, check out the utilities here: https://github.com/AntonyCorbett
And here: https://github.com/sircharlo/meeting-media-manager

**Comment by MrCyjaneK** [comment]
@livrasand could you link to the source of your app?

**Comment by MrCyjaneK** [comment]
@temporarium, that works for now but I feel like they are pushing web version away because of the mobile apps that are available. You can already see some exclusive content on jwlibrary that is not available to download in any archivable format.

**Comment by temporarium** [comment]
> @temporarium, that works for now but I feel like they are pushing web version away because of the mobile apps that are available. You can already see some exclusive content on jwlibrary that is not available to download in any archivable format.

What's public is available. Keep in mind that there a millions of people who cannot afford a mobile device, but may be able to access the web page ;-)

**Comment by livrasand** [comment]
Strongly agree with @MrCyjaneK about the organization focusing more on JWPUB. But I also considered your proposal @temporarium , however I think my intention is more focused on JWPUB. Finding nothing on the Internet ready-made, I started programming. So far I can already download the JWPUB file, unzip it and extract the Database (*.db), and connect to the database. Now I am trying to extract the information from the fields in the Multimedia table. I can share the code if you want to support me with ideas (which I would greatly appreciate).

**Form1.vb (Code)**
`Imports System
Imports System.Net
Imports System.IO.Compression
Imports System.IO
Imports System.IO.Compression.ZipFile
Imports System.Data.SQLite
Imports System.Collections
Imports System.Collections.Generic
Imports System.Data
Imports System.Windows



Public Class Form1
    Private Sub Button1_Click(sender As Object, e As EventArgs) Handles Button1.Click
        'Crea el directorio de descargas
        Try
            Label1.Text = "Creando el directorio de descarga temporal"
            My.Computer.FileSystem.CreateDirectory("C:\GoAttendant\Attendant Zoom\AppData\Local\Packages\417474656E64616E74205A6F6F6D")
        Catch ex As Exception
            MsgBox("No se pudo crear el directorio" & vbCrLf & ex.Message)
        End Try

        'Descarga el archivo
        Dim client As New WebClient()
        If My.Computer.Network.IsAvailable Then
            Try
                Label1.Text = "Descargando el archivo JWPUB..."
                My.Computer.Network.DownloadFile("https://download-a.akamaihd.net/files/media_periodical/c8/mwb_S_202207.jwpub", "C:\GoAttendant\Attendant Zoom\AppData\Local\Packages\417474656E64616E74205A6F6F6D\mwb_S_202207.jwpub")
            Catch ex As Exception
                MsgBox("No se pudo descargar el archivo JWPUB" & vbCrLf & ex.Message)
            End Try
        Else
            Label1.Text = "Conectate a Internet"
            MsgBox("No estás conectado a Internet")
        End If

        'Espera 5 segundos antes de continuar
        Try
            Label1.Text = "Espere 5 segundos..."
            System.Threading.Thread.Sleep(5000)
        Catch ex As Exception
            MsgBox("No se pudo esperar los 5 segundos" & vbCrLf & ex.Message)
        End Try

        'Cambia el nombre del archivo JWPUB a ZIP
        Try
            Label1.Text = "Cambiando el nombre al archivo JWPUB por ZIP"
            My.Computer.FileSystem.RenameFile("C:\GoAttendant\Attendant Zoom\AppData\Local\Packages\417474656E64616E74205A6F6F6D\mwb_S_202207.jwpub", "mwb_S_202207.zip")
        Catch ex As Exception
            MsgBox("No se pudo cambiar el nombre del archivo JWPUB" & vbCrLf & ex.Message)
        End Try

        'Descomprime el archivo ZIP
        Try
            Label1.Text = "Descomprimiendo archivo ZIP..."
            ZipFile.ExtractToDirectory("C:\GoAttendant\Attendant Zoom\AppData\Local\Packages\417474656E64616E74205A6F6F6D\mwb_S_202207.zip", "C:\GoAttendant\Attendant Zoom\AppData\Local\Packages\417474656E64616E74205A6F6F6D\")
        Catch ex As Exception
            MsgBox("No se pudo descomprimir el archivo ZIP" & vbCrLf & ex.Message)
        End Try

        'Espera 3 segundos antes de continuar
        Try
            Label1.Text = "Espere 3 segundos..."
            System.Threading.Thread.Sleep(3000)
        Catch ex As Exception
            MsgBox("No se pudo esperar los 3 segundos" & vbCrLf & ex.Message)
        End Try

        'Cambia el nombre de la carperta CONTENTS a ZIP
        Try
            Label1.Text = "Cambiando el nombre a la carpeta CONTENTS a ZIP"
            My.Computer.FileSystem.RenameFile("C:\GoAttendant\Attendant Zoom\AppData\Local\Packages\417474656E64616E74205A6F6F6D\contents", "contents.zip")
        Catch ex As Exception
            MsgBox("No se pudo cambiar el nombre de la carpeta CONTENTS" & vbCrLf & ex.Message)
        End Try

        'Descomprime la carpeta CONTENTS.ZIP
        Try
            Label1.Text = "Descomprimiendo la carpeta CONTENTS.ZIP..."
            ZipFile.ExtractToDirectory("C:\GoAttendant\Attendant Zoom\AppData\Local\Packages\417474656E64616E74205A6F6F6D\contents.zip", "C:\GoAttendant\Attendant Zoom\AppData\Local\Packages\417474656E64616E74205A6F6F6D\")
        Catch ex As Exception
            MsgBox("No se pudo descomprimir la carpeta CONTENTS.ZIP" & vbCrLf & ex.Message)
        End Try

        'Conexión a la BASE DE DATOS
        Dim SQLiteConn As New SQLiteConnection
        Try
            SQLiteConn.ConnectionString = "Data Source=C:\GoAttendant\Attendant Zoom\AppData\Local\Packages\417474656E64616E74205A6F6F6D\mwb_S_202207.db; Integrated Security=true"
            SQLiteConn.Open()
        Catch ex As Exception
            MsgBox("No se pudo conectar a la Base de Datos" & ex.Message)
        End Try

        'Conexión a la tabla Multimedia
        '
        Dim SQLitecmd As New SQLiteCommand
        Dim SQLiteReader As SQLiteDataReader
        Try
            SQLitecmd.CommandText = "SELECT * from Multimedia;"
            SQLiteReader = SQLitecmd.ExecuteReader()
            MsgBox(SQLiteReader("MimeType").ToString())
        Catch ex As Exception
            MsgBox("No se pudo conectar a la tabla Mutimedia" & ex.Message)
        End Try
    End Sub
End Class`

This is the part where I connect to the Multimedia table to extract data from the columns (KeySymbol Track MepsLanguageIndex IssueTagNumber), however I was unsuccessful.

_I use Google Translate, sorry if my translation is not good, I speak little English but not enough. I'm from Mexico._

**Comment by livrasand** [comment]
Once the project is finished I will make it public on GitHub for those who want to use it later.

**Comment by MrCyjaneK** [comment]
I can't run the app on my device, since this looks like a windows-only app.

Here are some resource that may be helpful for you:
https://github.com/MrCyjaneK/jwapi/blob/67f4ff8bd22dc8c4d6cc77074ba2f51b1d37c19c/docs/jwpub/pubcode_db/Multimedia.md <- multimedia table - all the images and filenames are inside the JWPUB file

https://github.com/MrCyjaneK/jwapi/tree/67f4ff8bd22dc8c4d6cc77074ba2f51b1d37c19c/docs/jwpub/pubcode_db

**Comment by MrCyjaneK** [comment]
> > @temporarium, that works for now but I feel like they are pushing web version away because of the mobile apps that are available. You can already see some exclusive content on jwlibrary that is not available to download in any archivable format.
> 
> What's public is available. Keep in mind that there a millions of people who cannot afford a mobile device, but may be able to access the web page ;-)

Im not sharing my ideas about what may happen but I'm telling you what is actually happening, you can't download [Insight on the Scriptures](https://www.jw.org/en/library/books/Insight-on-the-Scriptures/) in a format that can be nicely viewed on mobile (only an outdated PDF) or only jwpub in Polish https://www.jw.org/pl/biblioteka/ksi%C4%85%C5%BCki/Wnikliwe-poznawanie-Pism/, and in some places you can't use wol.jw.org simply because network there is so slow that it won't load when needed.

Also I don't feel like bringing the TOS is relevant here, but as a website owner I can say that scrappers are pain, instead of sending one request sometimes you need to send tens of them which put unnecessary load on the server - especially when an api is available.

**Comment by livrasand** [comment]
Yes, we are definitely on the same channel, I know what is inside the database, I normally use DB Browser to open the database. Now I require SQLite commands to extract that info, in sync with Visual Basic.

**Comment by livrasand** [comment]
### This conversation continues [here](https://github.com/darioragusa/JWLibrary-MediaInserter/issues/10)

**Comment by MrCyjaneK** [comment]
Let me close this one

**Comment by MrCyjaneK** [comment]
@livrasand it contains research that I don't want to lose, and I want it to be available in future

**Comment by MrCyjaneK** [comment]
and since I see that you have used the research to make profit I'm not willing to remove anything.

**Comment by MrCyjaneK** [comment]
@livrasand liar.
![Screenshot_20230624-183922_Fennec](https://github.com/MrCyjaneK/jwapi/assets/20381330/1aa8894b-6cc8-4ff4-b91f-d2463f81c9b1)

**Comment by MrCyjaneK** [comment]
So @bedan1, Where is the source code?

**Comment by orangethewell** [comment]
@bedan1 there's no reason to make it paid. Many brothers that developed any app or program as congregation helpers (like preaching management, meeting scheduling and other apps) made profit by donations, like TheocBase. Making profit from a program or app made for brothers and sisters just don't makes any sense, after all, the congregation pay bills with donations, why should people in there pay more for something not really necessary?

Anyway, with such a talent as a programmer, you should create another thing to make profit of. But, i'm not a lawyer, I don't know what you should do or do not.

**Comment by MrCyjaneK** [comment]
@orangethewell I as a person who sometimes visit the gray area of 'is it legal?' - people don't care until you make profit with that.
And @bedan1 (who changed name and is not the same account as @bedan1 who helped us) - is making profit out of somebody's else work and tries to to 'remain anonymous' and not share work.
Asshole move. End of topic.
