### ISSUE TITLE
404

### ISSUE THREAD

**Issue by vibbe** [MrCyjaneK/jwapi#24]
Q: could you please update the links, im getting a 404 error for most of the links. 
Perhaps your not working on this project anymore, but I would like to get hold of the deb files so I can install in in my linux system and look at it?

Thanks

**Comment by SFRS-MGFcompany** [comment]
I'm also having the same problem. Both binaries and repositories are 404.
This is currently the only project implementing jw-libray on Linux. I hope you recover.

**Comment by MrCyjaneK** [comment]
Nope. Build from source if you wish

**Comment by SFRS-MGFcompany** [comment]
Seriously? If so, let me guide you. I was a little worried that I had lost my motivation. But thank you.

**Comment by vibbe** [comment]
Well okay. Thaks for the reply at least.
