### ISSUE TITLE
Convertion .doc .pdf to format .jwpub

### ISSUE THREAD

**Issue by MaxBas70** [MrCyjaneK/jwapi#25]
I would like to know if there is a way to convert .doc (win word) or pdf files into **.jwpub** format, or if there isn't a system already done online, an idea on how to do it

**Comment by orangethewell** [comment]
.jwpub files are ZIP with HTML files on a database, there isn't a way to convert .doc or pdf to, at least you convert then to HTML and inject it to current HTML files inside the database.

**Comment by MrCyjaneK** [comment]
+1, if anything you can search for HTML to docx, but again I doubt this is what you want. There are plenty of metadata that you will lose along the way

**Comment by MrCyjaneK** [comment]
oh wait you want the other way around. Yea that won't happen.
