### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by peebowo** [MrCyjaneK/jwapi#3]
Hello! I was wondering how to call the jw.org api, or any documentation for it. Thanks!

**Comment by peebowo** [comment]
Also, how do you get the .jwpub file?

**Comment by MrCyjaneK** [comment]
Hey! I've just added an license so https://pkg.go.dev/git.mrcyjanek.net/mrcyjanek/jwapi will work (soon)

https://github.com/MrCyjaneK/jwapi/blob/59c4d833d3ce24d4a12c30e7528393d0f5f4366d/libjw/main.go#L656 here you have function to get publication, you can specify the format (for example `JWPUB` or what we use currently `EPUB`)

I'm in progress of adding support for JWPUB publications at the moment

**Comment by MrCyjaneK** [comment]
So @peebowo in #4 there is some initial support support for JWPUB. I'm closing this issue for now, feel free to open new one.

Docs are now here: https://pkg.go.dev/git.mrcyjanek.net/mrcyjanek/jwapi@v0.0.0-20210811154023-8291da22ca44/libjw
